# Note: It requires docker-compose 1.6.0+
#
# Usage: docker-compose up -d
version: '2'

services:
  # Selenium hub
    selenium_hub:
      image: hub.c.163.com/workhardsmile/citest:selenium-hub
      ports:
        - 4444:4444
      labels:
        aliyun.routing.port_4444: http://selenium/
    firefox:
      image: hub.c.163.com/workhardsmile/citest:selenium-node-firefox
      links:
        - selenium_hub
      labels:
        aliyun.scale: "3"
    chrome:
      image: hub.c.163.com/workhardsmile/citest:selenium-node-chrome
      links:
        - selenium_hub
      labels:
        aliyun.scale: "3"
    # Appium Docker Android
    appium_devices:
      image: hub.c.163.com/workhardsmile/citest:appium-grid
      ports:
        - 4723:4723
      depends_on:
        - selenium_hub
      network_mode: "service:selenium_hub"
      privileged: true
      volumes:
        - /dev/bus/usb:/dev/bus/usb
      environment:
        - CONNECT_TO_GRID=True
        - SELENIUM_HOST=selenium_hub
