#chmod -R 777 docker/testplus && docker network create -d bridge --subnet 192.169.100.1/24 testplus02
version: "2.0"

services:
  testplus-slave:
    image: 10.4.237.142:5001/slave:latest
    volumes:
        - ./docker/testplus:/test-slave
networks:
  default:
    external:
      name: testplus02