# encoding: UTF-8
# implement op-center test script op_center_sign_in
TargetService: 
plan_name: 'sample_web_testlink_login'
owner: wugang05@meituan.com
status: completed
created_dt: 2016-10-20
version: 1
last_modified_dt: 2016-10-20
timeout: 1200
actions: action_1

preconditions:
  - api_path: /users
    method: post
    request:
      name: "frank"
      username: ""
      password: "111111"
      repassword: "111111"
      level: ""
test_data:
  - request:
      username: ""
      password: ""
    expected:
      successs: false
      message: "用户名或密码均为空"
  - request:
      username: "testlink"
      password: ""
    expected:
      successs: false
      message: "密码均为空"
  - request:
      username: ""
      password: "123456"
    expected:
      successs: false
      message: "用户名为空"
  - request:
      username: "testlink"
      password: "111111"
    expected:
      successs: false
      message: "用户名或密码不正确"
  - request:
      username: "nouser"
      password: "111111"
    expected:
      successs: false
      message: "用户名不存在"
  - request:
      username: "testlink"
      password: "123456"
    expected:
      successs: true
      message: '账号密码正确'
  
