## Note: It requires docker-compose 1.6.0+
##
## Usage: docker-compose up -d
#version: '2'
#services:
#Selenium hub
hub:
  container_name: selenium-hub
  image: 10.4.237.142:5001/selenium-hub
  ports:
    - 4444:4444
  labels:
    aliyun.routing.port_4444: http://selenium/
firefox:
  container_name: selenium-node-firefox
  image: 10.4.237.142:5001/selenium-node-firefox
  links:
    - hub
  labels:
    aliyun.scale: "3"
  ports:
    - 5901:5900
chrome:
  container_name: selenium-node-chrome
  image: 10.4.237.142:5001/selenium-node-chrome
  links:
    - hub
  labels:
    aliyun.scale: "3"
  ports:
    - 5902:5900
#    # Appium Docker Android
#    appium_devices:
#      image: 10.4.237.142:5001/appium:grid
#      ports:
#        - 4723:4723
#      links:
#        - selenium-hub
#      #network_mode: "service:selenium-hub"
#      privileged: true
#      volumes:
#        - /dev/bus/usb:/dev/bus/usb
#      environment:
#        - CONNECT_TO_GRID=True
#        - SELENIUM_HOST=selenium_hub
# AVD_VERSION=19 && emulator -avd android-$AVD_VERSION -no-boot-anim & adb wait-for-device
appium_emulator:
  container_name: appium-emulator-vnc
  image: 10.4.237.142:5001/appium:emulator-vnc
  ports:
    - 4723:4723
    - 5903:5900
  privileged: true
