TargetService: CommerceServiceAdminUI##CommerceService##OfferService##CheckoutCui
plan_name: ''
owner: wugang05@meituan.com
status: completed
created_dt: 2015-07-03
version: 1
last_modified_dt: 2015-07-21
timeout: 1200
actions: action_block_1

data:
  agency_name: 'agency_20150624_1'
  post_url: 'http://endurance-vip.qa.aw.dev.activenetwork.com/endurance-management-service/soap/data-insight-service'
  html_css:
    name: "t20680css2015070101"
    level: "offer"
    css_content: ".csstest { font-size: 20px; line-height: 20px; color: #ff0000; background-color: #ffffff; }"
  soap_url:
    QA: 'http://commerce-vip.qa.aw.dev.activenetwork.com/commerce-service/soap/v1/offer'
    REG: 'http://commerce-vip.reg.aw.dev.activenetwork.com/commerce-service/soap/v1/offer'    
       