# encoding: UTF-8
# implement interface test script admin-articles-categories
TargetService: 
plan_name: 'sample_api_testlink_login'
owner: wugang05@meituan.com
status: completed
created_dt: 2016-10-10
version: 1
last_modified_dt: 2016-10-10
timeout: 1200
actions: action_1

api_path: /login.php
preconditions:
  - api_path: /lib/usermanagement/userInfo.php
    method: post
    request:
      doAction: "changePassword"
      oldpassword: "123456"
      newpassword: "123456"
      newpassword_check: "123456"
test_data:
  - method: post
    request:
      tl_login: ""
      tl_password: ""
    expected:
      code: 200
      sub_url: login.php
      message: "用户名或密码均为空"
  - method: post
    request:
      tl_login: "testlink"
      tl_password: ""
    expected:
      code: 200
      sub_url: login.php
      message: "密码均为空"
  - method: post
    request:
      tl_login: ""
      tl_password: "123456"
    expected:
      code: 200
      sub_url: login.php
      message: "用户名为空"
  - method: post
    request:
      tl_login: "testlink"
      tl_password: "111111"
    expected:
      code: 200
      sub_url: login.php
      message: "用户名或密码不正确"
  - method: post
    request:
      tl_login: "nouser"
      tl_password: "111111"
    expected:
      code: 200
      sub_url: login.php
      message: "用户名不存在"
  - method: post
    request:
      tl_login: "testlink"
      tl_password: "123456"
    expected:
      code: 200
      sub_url: index.php
      message: '账号密码正确'